#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : zVMCloudConnector
Version  : 1.3.0
Release  : 4
URL      : https://files.pythonhosted.org/packages/93/e3/4a8e10fd641fc9c765dc98f4487a2117cf39a635ecb37a179c783e505459/zVMCloudConnector-1.3.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/93/e3/4a8e10fd641fc9c765dc98f4487a2117cf39a635ecb37a179c783e505459/zVMCloudConnector-1.3.0.tar.gz
Summary  : z/VM cloud management library in Python
Group    : Development/Tools
License  : Apache-2.0
Requires: zVMCloudConnector-bin
Requires: zVMCloudConnector-python3
Requires: zVMCloudConnector-config
Requires: zVMCloudConnector-license
Requires: zVMCloudConnector-python
Requires: PyJWT
Requires: Routes
Requires: WebOb
Requires: jsonschema
Requires: netaddr
Requires: requests
Requires: six
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : tox
BuildRequires : virtualenv

%description
********************
        
        Description
        ===========
        z/VM cloud connector is a development sdk for manage z/VM. It provides a set of APIs to operate z/VM including guest, image, network, volume etc.
        
        Just like os-win for nova hyperv driver and oslo.vmware for nova vmware driver, z/VM cloud connector (zVMCloudConnector) is for nova z/vm driver and other z/VM related openstack driver such as neutron, ceilometer.
        
        Quickstart
        ==========

%package bin
Summary: bin components for the zVMCloudConnector package.
Group: Binaries
Requires: zVMCloudConnector-config = %{version}-%{release}
Requires: zVMCloudConnector-license = %{version}-%{release}

%description bin
bin components for the zVMCloudConnector package.


%package config
Summary: config components for the zVMCloudConnector package.
Group: Default

%description config
config components for the zVMCloudConnector package.


%package license
Summary: license components for the zVMCloudConnector package.
Group: Default

%description license
license components for the zVMCloudConnector package.


%package python
Summary: python components for the zVMCloudConnector package.
Group: Default
Requires: zVMCloudConnector-python3 = %{version}-%{release}
Provides: zvmcloudconnector-python

%description python
python components for the zVMCloudConnector package.


%package python3
Summary: python3 components for the zVMCloudConnector package.
Group: Default
Requires: python3-core

%description python3
python3 components for the zVMCloudConnector package.


%prep
%setup -q -n zVMCloudConnector-1.3.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1538151665
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/zVMCloudConnector
cp LICENSE %{buildroot}/usr/share/doc/zVMCloudConnector/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)
%exclude /var/lib/zvmsdk/setupDisk

%files bin
%defattr(-,root,root,-)
/usr/bin/gen-token
/usr/bin/sdkserver
/usr/bin/zvmsdk-wsgi

%files config
%defattr(-,root,root,-)
/usr/lib/systemd/system/sdkserver.service

%files license
%defattr(0644,root,root,0755)
/usr/share/doc/zVMCloudConnector/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
