#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : zVMCloudConnector
Version  : 1.4.1
Release  : 9
URL      : https://files.pythonhosted.org/packages/11/92/9f704de9759816e7b9897b9fb41285b421498b4642551b6fbcccd2850008/zVMCloudConnector-1.4.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/11/92/9f704de9759816e7b9897b9fb41285b421498b4642551b6fbcccd2850008/zVMCloudConnector-1.4.1.tar.gz
Summary  : z/VM cloud management library in Python
Group    : Development/Tools
License  : Apache-2.0
Requires: zVMCloudConnector-bin = %{version}-%{release}
Requires: zVMCloudConnector-license = %{version}-%{release}
Requires: zVMCloudConnector-python = %{version}-%{release}
Requires: zVMCloudConnector-python3 = %{version}-%{release}
Requires: zVMCloudConnector-services = %{version}-%{release}
Requires: PyJWT
Requires: Routes
Requires: WebOb
Requires: jsonschema
Requires: netaddr
Requires: requests
Requires: six
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : tox
BuildRequires : virtualenv

%description
z/VM Cloud Connector
********************
Description
===========
z/VM cloud connector is a development sdk for manage z/VM. It provides a set of APIs to operate z/VM including guest, image, network, volume etc.

%package bin
Summary: bin components for the zVMCloudConnector package.
Group: Binaries
Requires: zVMCloudConnector-license = %{version}-%{release}
Requires: zVMCloudConnector-services = %{version}-%{release}

%description bin
bin components for the zVMCloudConnector package.


%package license
Summary: license components for the zVMCloudConnector package.
Group: Default

%description license
license components for the zVMCloudConnector package.


%package python
Summary: python components for the zVMCloudConnector package.
Group: Default
Requires: zVMCloudConnector-python3 = %{version}-%{release}
Provides: zvmcloudconnector-python

%description python
python components for the zVMCloudConnector package.


%package python3
Summary: python3 components for the zVMCloudConnector package.
Group: Default
Requires: python3-core

%description python3
python3 components for the zVMCloudConnector package.


%package services
Summary: services components for the zVMCloudConnector package.
Group: Systemd services

%description services
services components for the zVMCloudConnector package.


%prep
%setup -q -n zVMCloudConnector-1.4.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1552668226
export LDFLAGS="${LDFLAGS} -fno-lto"
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/zVMCloudConnector
cp LICENSE %{buildroot}/usr/share/package-licenses/zVMCloudConnector/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)
%exclude /var/lib/zvmsdk/setupDisk

%files bin
%defattr(-,root,root,-)
/usr/bin/sdkserver
/usr/bin/zvmsdk-gentoken
/usr/bin/zvmsdk-wsgi

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/zVMCloudConnector/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*

%files services
%defattr(-,root,root,-)
/lib/systemd/system/sdkserver.service
